name: Test CI
on:
  pull_request:
  push:
    branches:
      - '!master'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm v8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm i

      - name: Test
        run: cd packages/lowcode-i18n-extract && npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yuntijs/lowcode-tools
          directory: ./packages/lowcode-i18n-extract/coverage/
